name: PowerShell 5 Experiment
on:
  workflow_dispatch:
jobs:
  windows-5.1-support-check:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-2016
          - windows-2019
          - windows-2022
      runs-on: ${{ matrix.runner }}
      steps:
        - run: |
            Get-Host
          shell: pwsh

        - run: |
            C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Get-Host"

        - run: |
            Get-Host
          shell: powershell

#  explore:
#    strategy:
#      fail-fast: false
#    runs-on: windows-2016
#    steps:
#      - run: |
#          dir C:\Windows\System32\WindowsPowerShell\
#
#      - run: |
#          C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Get-Host"
#
#      - run: |
#          Get-Host

#  experiment:
#    name: Install PowerShell 5
#    runs-on: windows-2016
#    steps:
#
#      # https://community.chocolatey.org/packages/PowerShell
#      # https://docs.chocolatey.org/en-us/choco/commands/install
#      - name: Installing WMF and PowerShell 5
#        run: |
#          choco install powershell --yes --force